<?php

namespace IDCI\Bundle\SimpleScheduleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * queryQueryBuilder
     *
     * @param array Parameters
     * @return QueryBuilder
     */
    public function queryQueryBuilder($params)
    {
        $qb = $this->createQueryBuilder('cat');
        $qb->orderBy('cat.parent', 'ASC');
        $qb->addOrderBy('cat.name', 'ASC');

        if(isset($params['level'])) {
            $qb
                ->andWhere('cat.level = :level')
                ->setParameter('level', $params['level'])
            ;
        }

        if(isset($params['ids'])) {
            $qb
                ->andWhere($qb->expr()->in('cat.id', $params['ids']))
            ;
        }

        return $qb;
    }

    /**
     * queryQuery
     *
     * @param array Parameters
     * @return Query
     */
    public function queryQuery($params)
    {
        $qb = $this->queryQueryBuilder($params);

        return is_null($qb) ? $qb : $qb->getQuery();
    }

    /**
     * query
     *
     * @param array Parameters
     * @return DoctrineCollection
     */
    public function query($params)
    {
        $q = $this->queryQuery($params);
        // Disable lazy loading
        //$q->setHint(\Doctrine\ORM\Query::HINT_FORCE_PARTIAL_LOAD, true);

        return is_null($q) ? array() : $q->getResult();
    }
}
