<?php

namespace IDCI\Bundle\SimpleScheduleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationAwareCalendarEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationAwareCalendarEntityRepository extends CalendarEntityRepository
{
    /**
     * queryQueryBuilder
     *
     * @param array Parameters
     * @return QueryBuilder
     */
    public function queryQueryBuilder($params)
    {
        $qb = parent::queryQueryBuilder($params);

        if(isset($params['location_id'])) {
            $qb
                ->andWhere('cer.location = :location_id')
                ->setParameter('location_id', $params['location_id'])
            ;
        }

        if(isset($params['location_ids'])) {
            $qb
                ->andWhere($qb->expr()->in('cer.location', $params['location_ids']))
            ;
        }

        return $qb;
    }
}
